[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "a49fa0d0c4afb13e5cf1b8bfb630bbf19d2c9a10"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "0f37d680c2e31064c8081674a25124db04aa36d83273e7a37195197fd6608797"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.3+1/cuPDLPx.v0.1.3.x86_64-linux-gnu-cuda+12.4.tar.gz"
