[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "93e024c1f90f258a48ff0d1a03eb9683c6e45f47"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "52cbaad357a5d0836972e18050ba4e097377b2305428dc9781e58cf8228ab084"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "fd3ef8978d93e940ae98d999b90fa5e425b673b5"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "9780b806332804e2f9f4e6af35097f3bc574f225200844534ab58aeaa2fe3b7c"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+1/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.4.tar.gz"
