[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "ec8a795df119a1165625013fd5450ed742981a1b"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "ba2127c340856715b6498b8970fd039bf8aa93c547705017fb8fe93e898fafbe"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.3+1/cuPDLPx.v0.1.3.x86_64-linux-gnu-cuda+12.5.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "74794a40a27fab1ef70e92e7b065da6adbf680f8"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "c81009605242c163f8a3d5bb0b56fa648911144b3ec7cdf3ba102e9d679bae2c"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.4.tar.gz"
