[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "fd3ef8978d93e940ae98d999b90fa5e425b673b5"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "9780b806332804e2f9f4e6af35097f3bc574f225200844534ab58aeaa2fe3b7c"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+1/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "fa4d8f3b1ca9ea6c0bc4dc9d5ed16504040969f6"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "91b44031c8974a70120a2fe62e10cd6fda0e6de2072524da76b35bba9e4e6298"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.2.2+1/cuPDLPx.v0.2.2.x86_64-linux-gnu-cuda+12.5.tar.gz"
