[[cuPDLPx]]
arch = "x86_64"
cuda = "12.4"
git-tree-sha1 = "74794a40a27fab1ef70e92e7b065da6adbf680f8"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "c81009605242c163f8a3d5bb0b56fa648911144b3ec7cdf3ba102e9d679bae2c"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.4.tar.gz"
[[cuPDLPx]]
arch = "x86_64"
cuda = "12.5"
git-tree-sha1 = "93e024c1f90f258a48ff0d1a03eb9683c6e45f47"
libc = "glibc"
os = "linux"

    [[cuPDLPx.download]]
    sha256 = "52cbaad357a5d0836972e18050ba4e097377b2305428dc9781e58cf8228ab084"
    url = "https://github.com/ZedongPeng/cuPDLPx_jll.jl/releases/download/cuPDLPx-v0.1.4+0/cuPDLPx.v0.1.4.x86_64-linux-gnu-cuda+12.5.tar.gz"
