name = "cuPDLPx_jll"
uuid = "bca5daad-f4d3-5101-ae12-8b63679c982c"
version = "0.1.4+0"

[deps]
JLLWrappers = "692b3bcd-3c85-4b1f-b108-f13ce0eb3210"
CompilerSupportLibraries_jll = "e66e0078-7015-5450-92f7-15fbd957f2ae"
Zlib_jll = "83775a58-1f1d-513f-b197-d71354ab007a"
CUDA_Runtime_jll = "76a88914-d11a-5bdc-97e0-2f5a05c973a2"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"

[compat]
JLLWrappers = "1.7.0"
julia = "1.10"
Libdl = "< 0.0.1, 1"
TOML = "< 0.0.1, 1"
Artifacts = "< 0.0.1, 1"
